### ISSUE TITLE
[Bug][AMS]: The optimize task property doesn't persist in MySQL after set 'max-execute-time'

### ISSUE THREAD

**Issue by hzluting** [NetEase/amoro#1000]
### What happened?

The optimize task property adds the key named 'max-execute-time' that doesn't persist in MySQL.
So if the AMS restarts,  the task will lose the property 'max-execute-time' value

### Affects Versions

0.3.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. create an arctic table
2. write the data into the table, and confirm optimizing task execution time over 30min
3. set the `self-optimizing.execute.timeout` as 3600000
4. restart the AMS when the optimizer executes the task
5. the task will always be failed because the execution expired

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@hzluting Can you add more information about the impact of the bug, like what will happen if the task lost it's `max-execute-time` property.

**Comment by hzluting** [comment]
We assume that we set the `self-optimizing.execute.timeout` value as 3600000(1 hour)
If the task lost the `max-execute-time` property, the AMS will use the default execution timeout(30 min) to check the task whether execution timeout.
This will cause the user's configuration can't be effective and the task can't be finished once it needs over 30 min.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
