### ISSUE TITLE
[Improvement][Flink]: Support customizing Arctic source parallelism

### ISSUE THREAD

**Issue by zstraw** [NetEase/amoro#1035]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Support customizing Arctic source parallelism, especially for log source.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
+1 for this improvement.
