### ISSUE TITLE
[Bug]: When the source table is not configured with watermark, double write does not take effect

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#1036]
### What happened?

If the configuration `arctic.emit.mode` is `auto` means flink writer operators will detect if the logstore is enabled automatically. If yes, the writer operators will double-write data into the logstore and filestore.

But if the writer operator didn't receive the watermark from the source operator(the source table didn't configure the watermark spec), the flink writers would not write records into the logstore. It does not meet the expectation.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink

### How to reproduce

```sql
create table arctic.flink_test.kafka_pk 
(id int, name string, dt timestamp, primary key(id) not enforced) 
with (
'log-store.enabled'='true',
'log-store.type'='kafka',
'log-store.topic'='arctic-testing',
'log-store.address'='*:*');

CREATE TABLE cdc_source(
  id      INT,
  name    STRING,
  op_time STRING
) WITH (
    'connector' = 'socket',
    'hostname' = 'localhost',
    'port' = '9999',
    'format' = 'changelog-csv',
    'changelog-csv.column-delimiter' = '|'
);

insert into arctic.flink_test.kafka_pk SELECT id,
        name,
        CAST(TO_TIMESTAMP(op_time) AS TIMESTAMP(6)) ts
 FROM cdc_source;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
As I know, the auto-writing to LogStore is dependent on the source watermark spec.
So how do you think the auto emit mode should behave when the source watermark spec is lack of?

**Comment by YesOrNo828** [comment]
@zhoujinsong If the watermark spec is lack of and Flink SQL Job does not configure the `arctic.emit.auto-write-to-logstore.watermark-gap`, I think the flink writer should execute the double-write operation.
