### ISSUE TITLE
[Improvement][Flink]: Flink hive adaptive should be 'metastore.uris' free

### ISSUE THREAD

**Issue by zstraw** [NetEase/amoro#1042]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

For now, if there is no metastore.uris configuration in hive-site.xml, it will encounter an error, like 
ERROR DataNucleus.Persistence                                      [] - Error : Could not find API definition for name "JDO". Perhaps you dont have the requisite datanucleus-api-XXX jar in the CLASSPATH?

It is inconvenient for some users who only config hive.server2.thrift.bind.host/port.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
`org.apache.iceberg.hive.CachedClientPool` use `metastore.uris` as key to cache client pools,
so `metastore.uris` is necessary for the native iceberg hive catalog.

We may should put this configuration info hive configuration if `hive-site.xml` lack of it.

**Comment by zhoujinsong** [comment]
But the reason why flink job will throw the exception is also unknown as ams is fine when connecting hive metastore.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
