### ISSUE TITLE
[Imporvement]: Arctic Terminal not support comments `#`

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1070]
### What happened?

When I write a comment with `#` in Arctic Terminal, it doesn't work.

However, `--` and `/*  */` work.

### Affects Versions

master/0.4.0/

### What engines are you seeing the problem on?

AMS

### How to reproduce

Type to Terminal like 
```
# comment
insert into test.table124 values (4,3)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/103108928/217207326-51d474c7-1225-4564-8b32-bccbfb822807.png">

**Comment by baiyangtx** [comment]
The `TerminalSessionContext.execute()`  has handled the line starting with `--`, adding an addition check could solve the problem.
