### ISSUE TITLE
[AMS][Bug]: When use native iceberg, update catalog properties does not take effect in terminal

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/amoro#1075]
### What happened?

When use native iceberg, update catalog properties then use terminal to execute sql, properties does not take effect

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

AMS

### How to reproduce

step1: create native iceberg catalog
step2: use terminal to execute sql
step3: update catalog properties
step4: use terminal to execute SQL agian 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
In the current local terminal backend, AMS holder spark context in the same process, and each catalog creates a spark session that shares the same spark context, and in the spark engine, the TableCatalog will be loaded once pre-context, so it is difficult to reload a native iceberg catalog.

In the long term, the local mode of terminal backend implementation should be sub-process and each process holds one spark context and the cancel action will kill the sub-process.
