### ISSUE TITLE
[Feature]: Support table repair in Spark

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/amoro#1098]
### Description

When table metadata is broken, we need an easier way to repair table metadata like https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-repair-table.html

### Use case/motivation

A SQL command to handle table metadata errors, such as

- Lost sub-table store, such as base or change table store can't be loaded.
- Lost some data files or metadata.json file

etc...

The command should analyze the reason the table load failed, and give a suggestion to repair the table and execution the repair suggestion.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
This bug(https://github.com/NetEase/arctic/issues/487) should be handled by this feature.

**Comment by shidayang** [comment]
doc see: https://docs.google.com/document/d/1KHQoNIJvxqB7qai2TUU3inlb8FZwpil4Xc2F5zvQbVg/edit#

**Comment by zhoujinsong** [comment]
Closed as a plan change.
