### ISSUE TITLE
[AMS][Bug]: Terminal  switch using catalog will throw exception 

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/amoro#1102]
### What happened?

Switch using catalog will throw an exception:
![image](https://user-images.githubusercontent.com/52364847/218443805-f68067bf-097e-4af2-ba7c-b96126092598.png)

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

AMS

### How to reproduce

step1: use a catalog with kerberos authentication and execute a query to a table
step2: switch to a catalog with simple authentication and execute a query to a table

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
This happened when switch catalog from kerberos to simple.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
