### ISSUE TITLE
[Improvement]: When the Metastore type is Custom, more flexible profile configuration should be supported

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/amoro#1109]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://user-images.githubusercontent.com/109209550/218697178-21e89c9b-c01b-40ce-b149-c0d04ebad8cd.png)
As shown, when the Metastore type is Custom, I can only configure hdfs-related core-site and hdfs-site, can not be configured hive-site or other more configuration files.
The limited configuration files do not give me the flexibility to use iceberg's custum catalog.

### How should we improve?

Supports more flexible profile configuration, allowing users to configure catalog more easily

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as has been supported.
