### ISSUE TITLE
[Improvement]: Clear useless files produced by the failed optimizing tasks avoid too many orphan files

### ISSUE THREAD

**Issue by hzluting** [NetEase/amoro#1177]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now, the optimizing tasks will auto retry when the tasks execute failed or commit failed, but the files produced by these tasks don't clear timely and become orphan files.
There will be too many orphan files if a table's tasks have always failed, so I want to clear the useless files produced by the failed optimizing tasks timely.

### How should we improve?

1. Optimizer clears the useless files produced by the failed tasks (avoid AMS clearing these files to need to list files in the HDFS)
2. AMS clears the useless files produced by the tasks when the commit failed
3. AMS clears the useless files produced by the prepared tasks when clearing the failed tasks after over-retry times
4. AMS clears the useless files and needs to consider the situation of repeat commit to avoid mis-delete valid files

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
