### ISSUE TITLE
[Bug][Optimize]: The manifest list file lost when optimize commit check

### ISSUE THREAD

**Issue by hzluting** [NetEase/amoro#1187]
### What happened?
For the unKeyed table support hive, the exception info is below when this table commits the major optimize result fails and tries to find committed data files to avoid misdelete.
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/5558252/222643030-d1342502-1501-4208-9acb-407abf36ccdf.png">

### Affects Versions

0.3.x,0.4.0

### What engines are you seeing the problem on?

AMS

### Anything else

1. I searched the log, and the expire snapshot didn't delete this snapshot.
2. This snapshot was produced by the Flink ingestion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
