### ISSUE TITLE
[Feature]: New operation and maintenance disk, monitoring system operation

### ISSUE THREAD

**Issue by hameizi** [NetEase/amoro#1219]
### Description

Increase the operation and maintenance board, provide monitoring `optimize` and `table runtime` indicators, and assist the operation and maintenance personnel to operate and maintain the system

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
