### ISSUE TITLE
[Improvement]: Improve resource utilization of parallel Optimizer 

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1242]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The Optimizer resource utilization is very lower(~10%) when I have an Optimizing Group with 100+ iceberg format tables and 20 parallelisms, and many tables are `Pending`.

The bottleneck may be the planning process since there is only one thread planning for all the tables.

The plan cost was as follows:

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/103108928/225648802-7611dc37-85df-4a27-ad6b-965de361f8df.png">

### How should we improve?

We should improve the plan performance or plan in parallel.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
I checked the code of the logs above:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/103108928/226504421-03b2f635-8fdd-43ac-88b1-923175d0a135.png">

the two main steps between `startTime` and `endTime`:
 - addOptimizeFiles
 - collectTasks
are not supposed to be time-consuming processes, since there are no io operations or lock waiting.

We'd better check the cpu occupancy and the cost of `gc` before further performance optimization.

**Comment by zhongqishang** [comment]
After troubleshooting, gc found no exceptions.

The most time consuming methods is `com.netease.arctic.ams.server.optimize.AbstractIcebergOptimizePlan#buildOptimizeTask `

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/16421989/227928185-7724e92d-5538-4616-9396-e50d306169d7.png">

There is access to HDFS within the method.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
