### ISSUE TITLE
[Feature]: Support integration with Apache Paimon

### ISSUE THREAD

**Issue by SteNicholas** [NetEase/amoro#1269]
### Description

Apache Paimon is streaming data lake platform with high-speed data ingestion, changelog tracking and efficient real-time analytics. Arctic could support integration with Apache Paimon.

### Subtasks

- [x] #1846
- [x] #1906 
- [x] #1871 
- [x] #1872 
- [x] #1873 
- [x] #1874 
- [x] #1875 
- [x] #1876 
- [x] #1877 
- [x] #1878 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Thanks a lot to bring this feature up!

Arctic is designed to manage Data Lake Tables of different formats.

I do think it is a great idea to integrate Paimon into Arctic and hope this can bring the Paimon users a better LakeHouse expirence.

**Comment by shidayang** [comment]
linked: #1844
