### ISSUE TITLE
[Feature]: Support Kubernetes deployment for AMS

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1335]
### Description

Support deploying AMS on Kubernetes.

### Use case/motivation

Kubernetes is one of the most popular and widely used container orchestration tools, supporting Kubernetes deployment can facilitate the use of AMS in cloud-native environments.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
Hi, I want to take this ticket and join this plan in RoadMap 0.5.0

**Comment by wangtaohz** [comment]
> Hi, I want to take this ticket and join this plan in RoadMap 0.5.0

Welcome to the Arctic community!  I assign this issue to you.
