### ISSUE TITLE
[Improvement]: Loading `Operations` Tab of Iceberg Format table with Hive metastore costs a long time

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1400]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

It costs a long time for Iceberg Format table to load `Operations` TAB, while the other TABs(Details, Transactions) load quickly. The Iceberg Format Table uses Hive as metastore.

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/103108928/234223983-e35824ab-a330-4b1a-bfdf-de43dd6854e3.png">

### How should we improve?

To check which step is time-consuming, and try to improve it.

The related code is here
`com.netease.arctic.ams.server.service.impl.DDLTracerService#getNativeIcebergDDL`
```
  public List<DDLInfo> getNativeIcebergDDL(ArcticCatalog catalog, TableIdentifier identifier) {
    List<DDLInfo> result = new ArrayList<>();
    ArcticTable arcticTable = catalog.loadTable(com.netease.arctic.table.TableIdentifier.of(identifier.getCatalog(),
        identifier.getDatabase(), identifier.getTableName()));
    Table table = arcticTable.asUnkeyedTable();
    List<HistoryEntry> snapshotLog = ((HasTableOperations) table).operations().current().snapshotLog();
    List<org.apache.iceberg.TableMetadata.MetadataLogEntry> metadataLogEntries =
        ((HasTableOperations) table).operations().current().previousFiles();
    Set<Long> time = new HashSet<>();
    snapshotLog.forEach(e -> time.add(e.timestampMillis()));
    for (int i = 1; i < metadataLogEntries.size(); i++) {
      org.apache.iceberg.TableMetadata.MetadataLogEntry e = metadataLogEntries.get(i);
      if (!time.contains(e.timestampMillis())) {
        org.apache.iceberg.TableMetadata
            oldTableMetadata = TableMetadataParser.read(table.io(), metadataLogEntries.get(i - 1).file());
        org.apache.iceberg.TableMetadata
            newTableMetadata = TableMetadataParser.read(table.io(), metadataLogEntries.get(i).file());
        genNativeIcebergDDL(arcticTable, oldTableMetadata, newTableMetadata, result);
      }
    }
    if (metadataLogEntries.size() > 0) {
      org.apache.iceberg.TableMetadata oldTableMetadata = TableMetadataParser.read(
          table.io(),
          metadataLogEntries.get(metadataLogEntries.size() - 1).file());
      org.apache.iceberg.TableMetadata newTableMetadata = ((HasTableOperations) table).operations().current();
      genNativeIcebergDDL(arcticTable, oldTableMetadata, newTableMetadata, result);
    }
    return result;
  }
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/103108928/234239465-f13d407b-69d0-4c7a-8dca-90f647494232.png">

**Comment by wangtaohz** [comment]
I think skipping the `metadata-log` which exists in `snaphot-log` by the `timestamp-ms` will bring a significant improvement.
Because the ddl (schema change or property change) can't produce a `snapshot-log`, and ddl is not supposed to be a frequent operation comparing to producing snapshot.



<img width="653" alt="image" src="https://user-images.githubusercontent.com/103108928/234268427-0cada63f-9eae-4336-a5e4-af9840e977f9.png">

**Comment by wangtaohz** [comment]
I only have 100 medata files, and it read medata files for 93 * 2 times.

**Comment by ZhendongBai** [comment]
@wangtaohz please assign to me, and I will submit a PR to optimize file read times.

**Comment by ZhendongBai** [comment]
@wangtaohz please assign to me, and I will submit a PR to optimize file read times.

**Comment by wangtaohz** [comment]
Okay, I will assign this issue to you. Before fixing it, you can briefly describe how to fix it under the issue.

**Comment by ZhendongBai** [comment]
@wangtaohz  I submitted a PR(https://github.com/NetEase/arctic/pull/1410) to improve performance, please review it if you have time.
