### ISSUE TITLE
[Improvement]: Spotless Maven Plugin Integration

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#1402]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I would like to improve the code quality of our project by integrating the Spotless Maven Plugin. This plugin can automatically format our code according to defined rules, ensuring consistency and readability throughout the codebase.

I propose to add the Spotless Maven Plugin to our project's build process and configure it to format our code according to the Arctic Checkstyle. This will help us maintain a clean and consistent codebase, making it easier for developers to understand and modify the code.

Welcome any feedback or suggestions on this proposed improvement.

### How should we improve?

To improve the situation, we could regularly review the Google Java Style Guide and update our code formatting rules accordingly. We could also consider using a tool that automatically updates our code formatting rules based on the latest version of the style guide. Additionally, we could provide training and resources to our developers to ensure they are aware of the latest style guide and understand how to write code that follows it. By staying up-to-date with the latest best practices for code formatting, we can ensure that our code is consistent, readable, and maintainable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- https://github.com/NetEase/amoro/issues/2017
- https://github.com/NetEase/amoro/issues/2018
- https://github.com/NetEase/amoro/pull/2108

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
I agree
