### ISSUE TITLE
[Improvement]: Improve the project documentation

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/amoro#1510]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

User documentation is one of the important means for users to understand and learn how to use a project.

The current user documentation of Arctic has the following shortcomings:

- No English documentation is provided, which limits the user group.
- There is no distinction between versions, which makes it difficult for users of previous versions to find the content they need.
- The documentation directory is not split reasonably, making it difficult for users to quickly find the content they want.

To address the above issues, we will optimize the documentation as follows:

- Provide an English version of the documentation.
- Split version-related and unrelated content for separate management.
- Optimize the directory structure.

### How should we improve?

We will complete the documentation optimization task through the following steps:

- Split version-related and version-unrelated content. Version-unrelated content will be managed in a separate project on the official website, while version-related content will still be managed together with the main project.
- Rearrange the document directory structure.
- Supplement and translate the existing documentation into English.

**It is worth noting that maintaining both English and Chinese documentation at the same time will bring a heavy workload. After this optimization, we will only keep the English documentation as the only language for continuous follow-up.**

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
The following sections, which are version-independent, will be split and maintained in a separate project on the official website:

- Overview
- Quick Start
- Benchmark
- Roadmap
- Contributing

**Comment by zhoujinsong** [comment]
The structure of the documentation will be adjusted as follows:

1. Concepts
1.1 Catalogs
1.2 Self-optimizing
1.3 Table watermark
2. Admin Guides
2.1 Deployment
2.2 Managing Catalogs
2.3 Managing Tables
2.4 Managing Optimizers
2.5 Using Kyuubi By Terminal
2.6 Metrics
3. Configurations
4. Engines
4.1 Overview
4.2 Flink
4.3 Spark
4.4 Trino
4.5 Impala

**Comment by zhongqishang** [comment]
@zhoujinsong 
Contributing part is simple, I remember there was a document for the community-developed spec[1], I think it should be added to help new developers contribute faster.

[1] : https://docs.google.com/document/d/1Pwv1LflW3z5yq34qDpEYwSxOB3LIE5qoKQ_5Sv0IV1Y
