### ISSUE TITLE
[Improvement]: Remove Deprecated configuration in the v0.5.0 version 

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/amoro#1582]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

0.5.0 is a big refactoring, I think the Deprecated configurations should be removed, and the technical debt should be reduced.

### How should we improve?

Remove the follow config:
- ENABLE_OPTIMIZE
- OPTIMIZE_GROUP
- OPTIMIZE_RETRY_NUMBER
- OPTIMIZE_MAX_FILE_COUNT
- FULL_OPTIMIZE_TRIGGER_MAX_INTERVAL
- MINOR_OPTIMIZE_TRIGGER_MAX_INTERVAL
- MINOR_OPTIMIZE_TRIGGER_DELETE_FILE_COUNT
- OPTIMIZE_QUOTA
- ENABLE_TABLE_EXPIRE_LEGACY
- ENABLE_ORPHAN_CLEAN_LEGACY
- READ_DISTRIBUTION_MODE
- READ_DISTRIBUTION_HASH_MODE
- ENABLE_LOG_STORE_LEGACY

And remove the use of these configurations.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@zhoujinsong @shidayang @wangtaohz  what do you think about this.

**Comment by baiyangtx** [comment]
The properties ending with `_LEGACY` are used by the older versions, we need to be compatible with tables created by older versions of the client.

**Comment by baiyangtx** [comment]
You can refer to https://github.com/NetEase/arctic/blob/master/core/src/main/java/com/netease/arctic/utils/CompatiblePropertyUtil.java

and 

https://github.com/NetEase/arctic/blob/master/hive/src/main/java/com/netease/arctic/hive/utils/CompatibleHivePropertyUtil.java

**Comment by zhoujinsong** [comment]
Compatibility with the table properties of old tables is a headache, and it is unlikely that this compatibility code will be kept in the project for a long time, which is not conducive to the long-term maintenance of the project code. However, when we remove the compatibility code, we must also provide a way for the historical tables to be correctly migrated to the new properties format to ensure that the user's table does not become unusable after upgrading to a certain version.

**Comment by zhongqishang** [comment]
> The properties ending with _LEGACY are used by the older versions, we need to be compatible with tables created by older versions of the client.

@baiyangtx Thanks for your remind. 
It is necessary to be compatible with the old properties, but I think we need to consider when to delete these deprecated configurations.

> we must also provide a way for the historical tables to be correctly migrated to the new properties format to ensure that the user's table does not become unusable after upgrading to a certain version.

I am more interested for `a way`, we can discuss how to reasonably delete these config.

**Comment by zhoujinsong** [comment]
These old properties existed before version 0.4.0 when the Arctic only supported Mixed Format tables, so we only need to consider the migration of Mixed Format tables.

One solution that I came up with is：

- Query the system database of Arctic to find tables that still used the old properties and add the new properties to these tables.
