### ISSUE TITLE
[Bug]: The arctic.emit.mode=auto parameter does not take effect in some scenarios. You need to manually specify arctic.emit.mode=file,log to write data to kafka at the same time

### ISSUE THREAD

**Issue by XiaoGerGer** [NetEase/amoro#1601]
### What happened?

1. There is a table with `log-store.enabled=false`, which is imported by a real-time flink sql task (in my case, the real-time data source is debezium)
2. Run the statement in the AMS Terminal to enable log-store. `alter table my_db.my_tb set properties('log-store.enabled'='true', 'log-store.topic'='mt_tb_topic', 'log-store.address' = '10.10.10.98:9092')`
3. Modify the data source. The real-time task inserts the data into the my_tb table. trino can query the newly inserted data, but there is no data in mt_tb_topic.
4. Restart the real-time task and continue to modify the data source (repeat step 3). trino can query the newly inserted data, but there is no data in mt_tb_topic.
5, replace the statement `insert into my_tb select * ...` with `insert into my_tb /*+ OPTIONS(' arctic.emite.mode '='log,file') */ select * ...`, mt_tb_topic has data, trino can also look up the latest data.

------------------------

Here's my detailed test case
```sql
-- 前提: flink sql-client 已开启 checkpoint，并且处于 streaming 模式
-- 版本：flink 1.15.2、artic-0.5.0（基于master分支编译）

-- 提示：该测试用例从内网截图用文字识别提取的，个别标点符号或字母错误不影响结果

-- 首先用任意工具(kafka 命令行，或者 kakfa UI 工具...)创建一个 topic，名称为 kafka_log_test_2

-- 创建 artic catalog
create catalog arc with (...);

-- 创建 arctic 表，用于承载数据
CREATE TABLE arc.ods.kafka_log_test_2 (
  val string,
  id BIGINT NOT NULL,
  PRIMARY KEY (id) NOT ENFORCED
) WITH (
  'write.upsert.enabled' = 'true'
);

-- 创建一张 kafka source 表，用于读取手动造的数据
create table kf_mock_data_as_source (
   id bigint,
   val string NULL
) with (
  'connector'= 'kafka',
  'topic'= 'kafka_log_test_2',
  'properties.bootstrap.servers' = '10.96.7.7:9092',
  'format'='json',
  'properties.group.id'= 'g1',
  'scan.startup.mode' = 'earliest-offset',
  'format'= 'json'
);

-- kafka >arctic，此处命名为 Job-1
insert into arc.ods.kafka_log_test_2 (id, val)
select id, val from kf_mock_data_as_source;

-- 接下来，通过任意方式(kafka 命令行，或者 kakfa UI 工具...), 向 kafka_log_test_2 中生产一条数据
-- {"id": 1,"val":"1"}

-- 稍等片刻，确保 trino 能查询到刚 id=1 的记录

-- 接下来，开启该表的 kakfa 双写
-- 在 AMS terminal 执行，开启 kafka_log_test_2 表的 log 双写加速
alter table ods.kafka_log_test_2 set tblproperties (
"log-store.enabled"="true",
"log-store.topic"="kafka_log_test_2_logstore",
"log-store.address"="10.96.7.7:9092"
);

-- 接下来，继续向 kafka_log_test_2 中生产一条数据
-- {"id": 2，"val":"2"}

-- 稍等片刻，确保 trino 能查询到刚 id=2 的记录，但去查看双写的 kakfa topic 中并没有 id=2 的记录

-- 接下来，重启 Job-1，(用来观察是否因为未重启导致的双写没生效)，重启成功之后，继续向 kafka_log_test_2 中生产一条数据
-- {"id": 3，"val":"3"}

-- 稍等片刻，确保 trino 能查询到刚 id=3 的记录，但去查看双写的 kakfa topic 中还是没有 id=3 的记录

-- 接下来，停止 job-1，将其语句改为如下运行，此处命名为 Job-2
insert into arc.ods.kafka_log_test_2 /*+ OPTION5('arctic.emit.mode'='log,file') */ (id, val)
select id, val from kf_mock_data_as_source;

-- 接下来，继续向 kafka_log_test_2 中生产一条数据
-- {"id": 4，"val":"4"}

-- 稍等片刻，确保 trino 能查询到刚 id=4 的记录，此时发现 kakfa topic 有了 id=4 的记录

-- 接下来，停止 Job-2，重新运行 Job-1，继续向 kafka_log_test_2 中生产一条数据
-- {"id": 5，"val":"5"}

-- 稍等片刻，确保 trino 能查询到刚 id=5 的记录，但去去查看双写的 kakfa topic 中又没有 id=5 的记录了

-- 问题:
-- 此处必须显示指定'arctic.emit.mode'='log,file'才能开启双写，默认的 auto 没有生效?

```

### Affects Versions

master-0.5.0

### What engines are you seeing the problem on?

Flink

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lklhdu** [comment]
the same as #1036, if the writer operator doesn't receive the watermark from the source operator(the source table didn't configure the watermark spec), the flink writers would not write records into the logstore. We will fix this issue later.
