### ISSUE TITLE
[Feature]: support flink optimize configuration for yarn.application.queue

### ISSUE THREAD

**Issue by xujiangfeng001** [NetEase/amoro#1777]
### Description

In yarn, different yarn queues are often created to allow different applications or users to run in different queues without interfering with each other.

And currently `flink optimize` unable to effectively specify `yarn.application.queue` during scale out, can only run in the `default queue`.Of course, users can configure `yarn.application.queue` in `flink-conf.yaml`, but I don't think this is particularly user-friendly for users.

I believe that Arctic needs to support users to specify `yarn.application.queue` when running `flink optimize`.

### Use case/motivation

I think three locations are needed for configuring `yarn.application.queue`, such as `flink-conf.yaml`, `container` and `scale-out`.Priority from low to high.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment]
cc @wangtaohz .

**Comment by wangtaohz** [comment]
I think it's reasonable to support setting `yarn.application.queue` in the `container` properties, but I'm not sure about the necessity of setting it during `scale-out`.

**Comment by xujiangfeng001** [comment]
> I think it's reasonable to support setting `yarn.application.queue` in the `container` properties, but I'm not sure about the necessity of setting it during `scale-out`.

My idea is to meet user usage scenarios as much as possible. This attribute is not a mandatory option in `scale-out`, so I think it is necessary to support `yarn.application.queue` on `scale-out`. If my ideas are wrong, please correct me.

**Comment by xujiangfeng001** [comment]
cc @YesOrNo828 @zhoujinsong @shidayang

**Comment by shidayang** [comment]
I think that scale-out is an engine and execution environment-independent operation, so it may not be appropriate to include it in scale-out. Containers are used to represent the execution engine and environment, so I agree that it should be included in containers.

**Comment by zhoujinsong** [comment]
> > I think it's reasonable to support setting `yarn.application.queue` in the `container` properties, but I'm not sure about the necessity of setting it during `scale-out`.
> 
> My idea is to meet user usage scenarios as much as possible. This attribute is not a mandatory option in `scale-out`, so I think it is necessary to support `yarn.application.queue` on `scale-out`. If my ideas are wrong, please correct me.

I agree that this improvement is very meaningful.

Multiple-level configuration is indeed more flexible. The meanings of different levels of configuration are:

- `flink-conf`: will affect all optimizers running with this flink configuration, usually affecting all optimizers applies in the cluster.
- `container`: will affect all optimizers in the container, containers are generally bound to a specific YARN cluster, so it can be understood that they affect all optimizers under a YARN cluster.
- `group`: will affect all optimizers in the group, a group is a virtual concept that represents a set of equivalent optimizers.
- `optimizer`: will affect one specific optimizer.

However, it seems like over-engineering to support configuration for each layer. Based on actual needs, I think opening configuration at the group level is sufficient.

**Comment by xujiangfeng001** [comment]
Thank you very much for your suggestions. I will submit the PR as soon as possible and support `yarn.application.queue` at the group level.
