### ISSUE TITLE
[Improvement]: Add env var ARCTIC_CONF_DIR to support assign config dir

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/amoro#1782]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add a new env var  ARCTIC_CONF_DIR to indicate a dir with arctic config.yml file

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Would it be better to directly specify the config file path, so that it does not limit the name of the config file?

**Comment by baiyangtx** [comment]
> Would it be better to directly specify the config file path, so that it does not limit the name of the config file?

Such behavior differs from the mindset of designing similar systems. Additionally, it would be inconvenient to specify this way if there are multiple configuration files. For example, there is still the configuration for log4j.xml.
