### ISSUE TITLE
[Bug]: When I upgrade a hive table and it fails, it deletes the original hive table.

### ISSUE THREAD

**Issue by nicochen** [NetEase/amoro#1807]
### What happened?

First I upgraded a hive table to a mixed hive table.
![image](https://github.com/NetEase/amoro/assets/4648576/e08325f2-c4a6-404e-b00f-ef77420b370c)
![image](https://github.com/NetEase/amoro/assets/4648576/62c02b3f-50aa-4e97-ac11-c81ddd559845)
You can tell I failed at this step.
![image](https://github.com/NetEase/amoro/assets/4648576/b3168d78-ebe5-4150-bb53-205efb0cb510)
However when I refreshed the page to load the table it no longer existed, later I went to hms to check that the table had been deleted before.
![image](https://github.com/NetEase/amoro/assets/4648576/5ed9ff98-ecdd-496d-8b9d-9ba141eb2e3f)

### Affects Versions

master

### What engines are you seeing the problem on?

Core, AMS

### How to reproduce

1. Create a hive table and upgrade it, and let it fail.
2. Check the hive table

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
This error could result in accidental deletion of Hive tables, posing a high risk. It should be fixed immediately in version 0.5.0.
