### ISSUE TITLE
[Improvement]: Check the validity of the heatbeat interval when an optimizer start 

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1810]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The configuration `optimizer.heart-beat-timeout` (default 60s) in AMS determines the lost timeout of the optimizer, and the `-hb` configuration of the optimizer determines the heartbeat interval. If the heartbeat interval is greater than the lost timeout configured in AMS, it will cause the optimizer to lost irregularly.

### How should we improve?

When the optimizer starts, it should check if the `-hb` configuration is less than AMS's `optimizer.heart-beat-timeout`. This check can be done when the optimizer registers to AMS.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tcodehuber** [comment]
Can you assign this issue to me?

**Comment by zhoujinsong** [comment]
> Can you assign this issue to me?

Sure, assigned.
