### ISSUE TITLE
[Improvement][AMS] keyed change table don't delete TTL files in time when expire

### ISSUE THREAD

**Issue by hzluting** [NetEase/amoro#185]
Now, keyed change table has 2 properties to control files
change.data.ttl.minutes: check change table data file whether in valid time, if not then delete from iceberg snapshot
snapshot.change.keep.minutes:check change table snapshot whether in valid time, if not then delete snapshot from file system(include deleted data files and metadata files)

so, the data files will keep ttlTime + expireTime.

**Comment by Aireed** [comment]
cc @hzluting    does it have been handled?

**Comment by hzluting** [comment]
> 

No, but now you can set the expire time to 0. The data files will delete after the TTL time.

**Comment by zhoujinsong** [comment]
Closed as not planed.
