### ISSUE TITLE
[Improvement]: Support application mode for Flink optimizer container

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/amoro#1855]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Flink Support 3 deployment modes which are `Per-Job mode`, `Application mode`, and `Session mode`.

For now, the Flink optimizer container support scaling out optimizer only in `Per-Job` mode which is deprecated actually.

We should support `Application mode` for the Flink optimizer container.

Since the `Session mode` requires starting the Flink cluster in advance, it doesn't seem suitable for launching the optimizer for now.

reference:https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/overview/

### How should we improve?

Support the application mode for the Flink optimizer container and make it to be the default mode.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
#1999
