### ISSUE TITLE
[Bug]:When using an HDFS cluster protected by Kerberos, the fs.hdfs.impl.disable.cache=false configuration is invalid, FileSystem is unable to hit the cache 

### ISSUE THREAD

**Issue by 861752346** [NetEase/amoro#1857]
### What happened?

Kerberos accounts usually consist of the principal and realm parts, in the form of principal@Realm. When using ams to create a catalog, since the uploaded krb5.conf file already contains the realm information, the account can be abbreviated to just fill in the principal. If the kerberos account information filled in during catalog creation is abbreviated, it will cause the FileSystem to be unable to hit the cache, constantly create new FileSystem instances without being garbage collected, eventually leading to an out of memory error.
It is recommended to modify the validation logic on line 239 of com.netease.arctic.table.TableMetaStore from !ugi.getUserName().equals(krbPrincipal) to !ugi.getUserName().startsWith(krbPrincipal) to adapt to the abbreviated kerberos account pattern.

### Affects Versions

0.5.0

### How to reproduce

When creating a catalog with Kerberos authentication, only the principal part is filled in the Kerberos principal field, without the realm information.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
Thank you very much for reporting this issue and identifying the root cause.

Would you be interested in fixing this problem?

**Comment by 861752346** [comment]
Would you be interested in fixing this problem?

**Comment by 861752346** [comment]
Yes, I'm interested in fixing this problem.

**Comment by wangtaohz** [comment]
> Yes, I'm interested in fixing this problem.
@861752346 Can you submit a PR to fix this issue? I'd like to include this fix in the 0.5.1 road map. 😄
