### ISSUE TITLE
[Bug]: Iceberg mixed partition table, amoro UI display and merged write directory error

### ISSUE THREAD

**Issue by archer2012** [NetEase/amoro#1863]
### What happened?

**This table use month-day mixed partitioning.**
![c42459ec59d06a9b226943c83b71b58](https://github.com/NetEase/amoro/assets/3227239/4a394850-a613-46bd-b4e9-481b8f84b5a2)
![f1d9fb44e27c871e167bca3992384a3](https://github.com/NetEase/amoro/assets/3227239/e7c30762-444d-4247-b136-9f5c5c9dccf9)

amoro UI display and merged write data to directory error(1970-xx-xx)
![c0c99ad85398833a9387ba61830c70b](https://github.com/NetEase/amoro/assets/3227239/3e0a4f57-ca72-47cd-84cc-b626f5dd7d8d)

### Affects Versions

0.5.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

```
create table t1(id int, create_at timestamp) partition sep month(create_at) stored as iceberg tblpropertises('format'='v2');

insert into t1(1,'2022-01-01 01:00:00');
insert into t1(2,'2022-02-01 01:00:00');
insert into t1(3,'2022-03-01 01:00:00');
 
alter table t1 replace partition day(create_at);

insert into t1(1,'2023-01-01 01:00:00');
insert into t1(2,'2023-02-01 01:00:00');
insert into t1(3,'2023-03-01 01:00:00');
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Thank you for reporting this issue. We need to confirm some details, but if I understand correctly, the problem is that after modifying the partition of Iceberg, the partition of the output data file is incorrect after self-optimizing, right?

**Comment by zhoujinsong** [comment]
It seems that the reason for the issue is that when Iceberg contains files with multiple Partition Specs, Amoro currently uses the current Partition Spec to process all files in both file display and self-optimizing processes, which is incorrect and may cause problems that the issue described.
