### ISSUE TITLE
[Bug]:  the historical metadata file has not been deleted

### ISSUE THREAD

**Issue by archer2012** [NetEase/amoro#1864]
### What happened?

The optimizing process has been successfully executed and the historical metadata json file has not been deleted. 

```
alter table xx set tblproperties (
 'self-optimizing.enabled' = 'true',
 'self-optimizing.group' = 'xx-amoro-group1',
 'engine.hive.enabled' ='true',
 'clean-orphan-file.enabled' = 'true',
 'snapshot.base.keep.minutes'='120',
'table-expire.enabled'='true'
 );
```

![6c89a1050eddac74df8a111a865d0d9](https://github.com/NetEase/amoro/assets/3227239/8e13883b-7884-41b8-a82c-55df8ae7d6d4)
<img width="1777" alt="4b43d7782301fcd7f9337451f0793cb" src="https://github.com/NetEase/amoro/assets/3227239/f9ff7622-7948-457a-9b49-961ceed86d44">

### Affects Versions

0.5.x

### What engines are you seeing the problem on?

AMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Thank you for reporting the bug. I will check into this issue.
