### ISSUE TITLE
[Bug]: Segment file first binpack strategy leads to inability to optimize SplitTasks

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#1866]
### What happened?

![image](https://github.com/NetEase/amoro/assets/54210725/97f3e35c-02ec-40ea-b772-a273453235ea)
OptimizeEvalutor found some partitions that need to optimize, but Planer didn't get any tasks.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. enable self-optimizing for the Iceberg table which has a certain number of segment files
2. write some fragment files

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majin1102** [comment]
Thanks for feeding back.
Is there any more conditions to reproduce this situation?

**Comment by XBaith** [comment]
> Thanks for feeding back. Is there any more conditions to reproduce this situation?

I believe this case would happen if there are a certain number of segment data files in the table
