### ISSUE TITLE
[Feature]: Support table filters to make AMS ignore tables that are not needed

### ISSUE THREAD

**Issue by celltobig** [NetEase/amoro#1870]
### Description

I want table filter ,  but now catalog  database tables is full show

### Use case/motivation

I want table filter ,  but now catalog  database tables is full show,so add table filter 

### Describe the solution

add a table filter to list  I want see the table  

### Related issues

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
Thanks for your bring up this feature. AFAIK, Currently, the list display of the table has a filter. What specifically do you mean by "filter" that you mentioned?
<img width="607" alt="image" src="https://github.com/NetEase/amoro/assets/26699250/69d0b4e2-44b5-45a8-99c7-7aca71cddfe8">

**Comment by wangtaohz** [comment]
I think "table filter" here refers to ignoring some tables when loading tables from a catalog/database, rather than filtering on the WebUI. Maybe you can provide more information on how to implement it? @celltobig 

And I think it's a common requirement. Looking forward to your PR. 😄

**Comment by wangtaohz** [comment]
BTW, you could expand the title to help other developers better index this issue. @celltobig
