### ISSUE TITLE
[Improvement]: Improve the SQL Shortcuts in Terminal Web UI

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#1892]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the SQL Shortcuts feature is not user-friendly because it overrides all SQLs in the terminal, causing previous SQLs to be lost.

<img width="630" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/b61f5563-70bf-4118-814e-9ac8cd118638">

### How should we improve?

Maybe we should append the new SQL demo to the last line instead of overriding all the SQLs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
Also, there is currently a lack of a SQL demo on dropping table properties, which should be
```
ALTER TABLE arctic_catalog.db.sample UNSET TBLPROPERTIES ('read.split.target-size');
```

**Comment by tcodehuber** [comment]
Can you assign this issue to me?

**Comment by zhoujinsong** [comment]
> Can you assign this issue to me?

Assigned.
