### ISSUE TITLE
[Bug]: Start Ams in IDEA Error

### ISSUE THREAD

**Issue by Pandas886** [NetEase/amoro#1897]
### What happened?

I wanted to contribute for amoro, so I tried to run the AMS in IDEA, but encountered an error. 

Before starting, I had successfully executed ' mvn clean install -pl '!trino'  -B -ntp  -DskipTests  l' in the command terminal.

![image](https://github.com/NetEase/amoro/assets/123344357/8154e5e3-9d62-437a-9071-1dfb88208e26)
![image](https://github.com/NetEase/amoro/assets/123344357/b4bc0f31-1841-4e93-9c97-968d590016eb)

### Affects Versions

0.5.x branch

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Did you select the profile for Hadoop 2 or Hadoop 3?  

Alternatively, you can try "Maven reimport".
