### ISSUE TITLE
[Bug]: Using mix iceberg in spark has some docs problems

### ISSUE THREAD

**Issue by HuangFru** [NetEase/amoro#1908]
### What happened?

I want to use mix iceberg catalog in Spark and I set it up according to the official website documentation :
![image](https://github.com/NetEase/amoro/assets/68625618/a895798e-ec5f-456a-9193-4b08c99a25d2)

Then I ran into the following error:
![截屏2023-09-01 11 12 25](https://github.com/NetEase/amoro/assets/68625618/823c5994-fd27-45ae-b120-ea98c5ee58b7)
![截屏2023-09-01 11 14 49](https://github.com/NetEase/amoro/assets/68625618/ddbff415-6d34-4d12-8a66-756cc06408e7)
It seems the names of these classes have not changed from 'Arctic' to 'Amoro' yet. After I change the name to 'Arcitc', it works fine.

### Affects Versions

master

### What engines are you seeing the problem on?

Spark

### How to reproduce

Using mix iceberg catalog according to the official website documentation.

### Relevant log output

```shell
See "What happened".
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HuangFru** [comment]
BTW, there are still many classes and variables using ‘Arctic’ in the current Amoro project code. Should we modify them uniformly?

**Comment by baiyangtx** [comment]
The class still be `ArcticSparkExtensions`

**Comment by zhoujinsong** [comment]
We have not changed the package and class name for renaning Project name.
Therefore, the content in the document is wrong, can you help to correct it?

**Comment by HuangFru** [comment]
> We have not changed the package and class name for renaning Project name. Therefore, the content in the document is wrong, can you help to correct it? @HuangFru

Sure
