### ISSUE TITLE
[Improvement]: Documents about intergration with kubernetes

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/amoro#1918]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Adding documents about integration with Kubernetes.

- Add a subpage "Deploy AMS on Kubernetes" to the "deployment" section of the documentation.
- Add a subpage "Deploy Optimizer on Kubernetes" to the "deployment" section of the documentation.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
take this task @baiyangtx
