### ISSUE TITLE
[Bug]: The optimizing task has been in a suspended state all along.

### ISSUE THREAD

**Issue by shidayang** [NetEase/amoro#1939]
### What happened?

<img width="987" alt="image" src="https://github.com/NetEase/amoro/assets/26699250/cf1fdc76-879c-4577-8d0f-0314ceefdcf7">
The table has been in a running state all along, and it was found that a task has been in a schedule state, which caused the issue. The task has been in a schedule state due to two reasons. Firstly, during the process of expiring tokens, the pollTask and ackTask of optimizing used different tokens, causing an ack failure and the task to be in a schedule state. Secondly, due to the concurrent modification of other task states, the status of the task has already been successful, but it still exists in the executingTaskMap of the OptimizingQueue, causing checkSuspending to report errors continuously and failing to reschedule the task in the schedule state.

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
**the pollTask and ackTask of optimizing used different tokens,**

What caused this? Did the Optimizer restart?
