### ISSUE TITLE
[Improvement]: Support list partitions via flink catalog

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#1940]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now the flink catalog is not implemented `public List<CatalogPartitionSpec> listPartitions(ObjectPath tablePath)` interface; so `SHOW PARTITIONS` statement is not supported.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
I can complete this part of the work, but from my practice, listing all partitions will definitely scan all metadata. For some large tables, this may take a long time, which will put a certain amount of pressure on the flinkclient that runs the statement.

**Comment by YesOrNo828** [comment]
> I can complete this part of the work, but from my practice, listing all partitions will definitely scan all metadata. For some large tables, this may take a long time, which will put a certain amount of pressure on the flinkclient that runs the statement.

@huyuanfeng2018  Thanks for volunteering to fix it. I've assigned it to you. I think your consideration is reasonable, and we also need to scan two tables including the change and base table, if the mixed-format table is a Keyed Table.
