### ISSUE TITLE
[Feature]: AMS Support Database Secert On K8S

### ISSUE THREAD

**Issue by czy006** [NetEase/amoro#1945]
### Description

Currently, the database password is written to the configuration file in plain text, which may pose certain security risks. In the cloud-native environment, this configuration will be saved through K8S Secert, which will improve password security.

### Use case/motivation

After discussing with [pull request](https://github.com/NetEase/amoro/pull/1909), we decided to separate and complete this part of the function, which will improve the security of database passwords

### Describe the solution

The Secert mount function only supports running on K8S

- Mount the Secert or get the password by reading the environment variable, and decode it through base64
- The environment variable name is: DATABASE_PASSWORD
- Read Priority: Environment Variables > Configuration Files
  - If the deployment environment is K8S, the variable will be read from the environment variable and the base64 deserialized password will be performed. The user only needs to set the password in the configuration file, and it will be automatically set to Env in Secert mode, which is read by the program, and there is no need to care about this part of the implementation.
  - If the deployment environment is a non-K8S environment, first read from the environment variable, if it is empty, then read directly from the configuration file, this part will not have any encryption behavior

### Related issues

None

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@czy006 Thanks a lot to bring this feature up!
[Kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret/) is the standard method for storing the sensitive information. Based on it, the configuration security of AMS in K8S environment can be greatly improved.

The impelemntation look fine to me. I am looking forward to seeing your PR.

**Comment by baiyangtx** [comment]
Thank you for proposing this feature. I think this feature is very important for production deployment and K8S cluster deployment.  I am looking forward to seeing your PR.

**Comment by czy006** [comment]
Secert On K8S Pwd [Demo](https://kubernetes.io/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure/#convert-your-secret-data-to-a-base64-representation)
