### ISSUE TITLE
[Improvement]: javalin version bump to 4.6.8

### ISSUE THREAD

**Issue by czy006** [NetEase/amoro#1946]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

javalin version bump to 5.6.2

### How should we improve?

- upgrade **io.javalin** pom version to 5.6.2
- Migrate removed or expired javalin method

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
Thank you for raising this issue!

Can you briefly explain what drives us to upgrade javalin version to 5.6.2?

**Comment by czy006** [comment]
5.0 has major improvements in performance and security. Keeping updated helps avoid being too far behind in versions, making subsequent upgrades difficult. cc @wangtaohz 

https://github.com/javalin/javalin/issues/1517

**Comment by baiyangtx** [comment]
To my knowledge, there are compatibility issues between the current version of Javalin and OpenJDK 8.  

Does downgrading the version to 5.6.2 solve the compatibility issue with OpenJDK 8?

**Comment by czy006** [comment]
Javalin is written in Kotlin, so we don't quite care about Java version that much.I will try to see if the JDK8 compilation is supported. By the way, the majority of projects in the community are currently moving towards JDK11 as the default build, so I think it's important to recommend that users use JDK11 by default and remove support for JDK8 in the future (that's another topic, of course).

https://github.com/javalin/javalin/issues/1517#issuecomment-1162023847

**Comment by czy006** [comment]
After I checked carefully, I found that the minimum requirement of jetty11 is jdk11, so this upgrade can only be temporarily organized.

cc @baiyangtx

**Comment by baiyangtx** [comment]
> After I checked carefully, I found that the minimum requirement of jetty11 is jdk11, so this upgrade can only be temporarily organized.
> 
> cc @baiyangtx

What is the latest version of Javalin that supports JDK8? Can we upgrade it further?

**Comment by czy006** [comment]
4.8.6 is the latest version of the current 4.x, maybe we can upgrade it. However, part of the API has been deprecated in 5.x and 6.x, and we can only upgrade to this version at present

**Comment by baiyangtx** [comment]
> 4.8.6 is the latest version of the current 4.x, maybe we can upgrade it. However, part of the API has been deprecated in 5.x and 6.x, and we can only upgrade to this version at present

We can upgrade to 4.8.6
