### ISSUE TITLE
[Bug]: Terminal has time zone problem with timestamp

### ISSUE THREAD

**Issue by HuangFru** [NetEase/amoro#1968]
### What happened?

When setting the time zone in the Terminal with `spark.sql.session.timeZone` like this :
![image](https://github.com/NetEase/amoro/assets/68625618/aeed40c5-653d-4a9d-94b3-fb2fa1574914)

And then execute the 'select' statement to read from a table, The config did not take effect.

Spark does not support timestamps without the time zone. So when reading a timestamp without a time zone type written by Flink, Spark will add a local time zone and will cause a time difference. So we need to set `spark.sql.session.timeZone` to 'UTC' to avoid this situation. I have already verified this in the Spark environment.

However, this config does not take effect in the AMS terminal when reading data. According to https://stackoverflow.com/questions/49644232/how-to-set-timezone-to-utc-in-apache-spark, 
There may be implicit conversions in the process of executing Java code and returning results in the terminal.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

Create a mix-iceberg table in the Flink with a time stamp filed(without time zone).

Write some data.

Read in the Terminal.

### Relevant log output

```shell
Write:
1	aaa	2015-10-11 00:00:00.0

Read in terminal:
1	aaa	2015-10-11 08:00:00.0
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
You have set to use a timestamp without zone.

**Comment by HuangFru** [comment]
> You have set to use a timestamp without zone.

Even if I set `local.spark.sql.iceberg.handle-timestamp-without-timezone` to true, it doesn't work either.

**Comment by zhoujinsong** [comment]
> > You have set to use a timestamp without zone.
> 
> Even if I set `local.spark.sql.iceberg.handle-timestamp-without-timezone` to true, it doesn't work either.

Have you found the reason why the configuration is not taking effect? I believe that the first step in fixing a problem is to identify the root cause.

**Comment by HuangFru** [comment]
> > > You have set to use a timestamp without zone.
> > 
> > 
> > Even if I set `local.spark.sql.iceberg.handle-timestamp-without-timezone` to true, it doesn't work either.
> 
> Have you found the reason why the configuration is not taking effect? I believe that the first step in fixing a problem is to identify the root cause.

I don't think the configuration takes effect in this situation. This is an iceberg configuration that controls whether to handle timestamps without the time zone. When set to false, Iceberg will throw an exception when reading timestamp without time zone:
<img width="1247" alt="image" src="https://github.com/NetEase/amoro/assets/68625618/285e8f6d-25d2-4a4e-b87f-14cd194d4229">
This configuration in Mix-iceberg only handles the new table created by the spark. Controls whether to convert the timestamp column. Not take effect here.

**Comment by HuangFru** [comment]
set `spark.sql.datetime.java8API.enabled` to true could solve this issue.
Reflected in the terminal:
![image](https://github.com/NetEase/amoro/assets/68625618/ae11c0df-2ef0-48b1-be19-a7a8f2b805a7)
