### ISSUE TITLE
[Bug]: If the iceberg table has a primary key of date type, in upsert mode, after Amoro merge, the primary key duplicate data can be found

### ISSUE THREAD

**Issue by MrDannyWu** [NetEase/amoro#1979]
### What happened?

When I use Amoro to merge the iceberg table, when the iceberg table has a primary key of date type, in upsert mode, flink can successfully upsert, but after the Amoro merge, duplicate data in the primary key can be found.

### Affects Versions

master 

### What engines are you seeing the problem on?

Optimizer

### Flink SQL create iceberg table
```
CREATE TABLE hive_iceberg.test_dwd.table_iceberg_demo(
    d1 date,
    d2 string,
    d3 string,
    v1 bigint,
    v2 bigint,
    v3 bigint,
    v4 bigint,
    v5 bigint,
    v6 bigint,
    v7 bigint,
    v8 bigint,
    v9 bigint,

PRIMARY KEY (`d1`, `d2`, `d3`) NOT ENFORCED
)
with (
'format-version'='2',
    'iceberg.mr.catalog'='hive',
    'engine.hive.enabled'='true',
    'write.upsert.enabled'='true',
    'write.metadata.previous-versions-max'='3',
    'hive.vectorized.execution.enabled'='false',
    'write.metadata.delete-after-commit.enabled'='true',
    'warehouse'='hdfs://nameservice1/user/hive/warehouse/test/table_iceberg_demo'
    );
```

### Flink SQL insert data
```
insert into hive_iceberg.test_dwd.table_iceberg_demovalues (TO_DATE('2023-09-20'),'values1','1',300,0,0,0,0,0,0,0,0);
insert into hive_iceberg.test_dwd.table_iceberg_demovalues (TO_DATE('2023-09-20'),'values1','1',123,0,0,0,0,0,0,0,0);
```
* Before Amoro merged, I only queried the latest data. (this is normal)

* After waiting for Amoro to merge, two pieces of data were queried.(It's not normal)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by czy006** [comment]
Can you supplement the used amoro, flink and some environment versions so that we can locate it faster ～

**Comment by MrDannyWu** [comment]
Flink 17.1
