### ISSUE TITLE
[Bug]:  ams-optimizer FLINK job expired oom due to frequent requests for Kerberos.

### ISSUE THREAD

**Issue by archer2012** [NetEase/amoro#1980]
### What happened?

When the optimizer FLINK job runs for a period of time, frequent oom will occur.
![73cd4fc7c34948cda96fc375ab05dd8](https://github.com/NetEase/amoro/assets/3227239/5fef57f5-c7d6-4124-8c3c-a4c858044c77)

In Amoro's code, there is Cache where TableMetaStore is created, so this object will not be repeatedly created, but the object query fails when the Cache is serialized. . 

![7ad8057dc08ce963eb45b537bcd2cd1](https://github.com/NetEase/amoro/assets/3227239/c4ede4ef-f302-4951-b86d-efd1860e6809)

### Affects Versions

0.5x

### What engines are you seeing the problem on?

Optimizer

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
The Optimizer obtains the TableMetaStore through deserialization, which bypasses the cache mechanism of the TableMetaStore object, resulting in the creation of a new TableMetaStore object each time a Task is executed. This will cause duplicate construction of UGI objects and cause the FileSystem cache to miss.

**Comment by baiyangtx** [comment]
![图片](https://github.com/NetEase/amoro/assets/7732224/2eedbef7-2f64-4bc3-b394-06a1cab0f453)
