### ISSUE TITLE
[Feature]: Upgrading Flink version based on Mixed-format table

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#1983]
### Description

In terms of [Disscussion-1937](https://github.com/NetEase/amoro/discussions/1937), we conclude that flink modules will extract the public modules to support different versions of the Flink, and will only keep the three latest flink versions in the future, which will greatly reduce maintenance costs and make UTs easier!

The code of the flink public modules will depend on the latest flink version, e.g. 1.17 now, and any conflicts between api's of different Flink versions will be resolved in other versions.

/flink
|---/v1.15
|------/flink #fix the confict with 1.17 API
|------/flink-runtime #shaded 
|---/v1.16
|------/flink #fix the confict with 1.17 API
|------/flink-runtime #shaded 
|---/v1.17
|------/flink 
|------/flink-runtime #shaded 
|---/flink-common #dependence the newest flink version 1.17
|---/flink-common-format #dependence the newest flink version 1.17

### Describe the solution

- Support Flink 1.17 based on the Flink common module
- Support Flink 1.16 based on the Flink common module
- Remove Flink 1.12
- Remove Flink 1.14
- Adjust Flink 1.15 based on the Flink common module

- [x] #2059

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
After offline synchronization, our common module determined to use 1.17 code, and tried to make the 1.15 code compatible with 1.17. I am willing to take on this part of the work. @YesOrNo828

**Comment by YesOrNo828** [comment]
@czy006 could you create a subtask issue related to #1983 to support 1.17?
