### ISSUE TITLE
[Improvement][Flink] Adding support for setting/altering Arctic table properties

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#2]
### Search before asking

- [x] I have searched in the [[issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue)](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?
Enhancing the ability of Flink SQL to operate Arctic tables, allowing users to modify table properties through the `alter table` syntax.
Set or Alter Table Properties
```sql
ALTER TABLE [catalog_name.][db_name.]table_name SET (key1=val1, key2=val2, ...)
```
Set one or more properties in the specified table. If a particular property is already set in the table, override the old value with the new one.

### How should we improve?

-  Implement the `ArcticCatalog.alterTable` method.
-  Invoking the AMS API to alter the properties.
-  Add some UTs with the Flink Catalog API and Flink SQL.
-  Affected Flink versions: flink1.12/flink1.14/flink1.15.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [[Code of Conduct](https://www.apache.org/foundation/policies/conduct)](https://www.apache.org/foundation/policies/conduct)

**Comment by DKolibar** [comment]
Hello, @YesOrNo828 , is this issue still relevant for this project? If yes, I would like to work on it.

**Comment by zhoujinsong** [comment]
> Hello, @YesOrNo828 , is this issue still relevant for this project? If yes, I would like to work on it.

Yes, We are very welcome for your contribution!
