### ISSUE TITLE
[Improvement][docs]: Introduce the Lookup Join with mixed-format table via Flink 

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#2002]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

After finished the #1322, we should complete Flink lookup join guide for mixed-format table in manual. 

Flink SQL Syntax: https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/table/sql/queries/joins/#lookup-join

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
take it
