### ISSUE TITLE
[Bug]: `table-filter` doesn't work for the internal catalog

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2011]
### What happened?

Amoro now supports configuring a property on catalog to filter out tables, but currently, this filtering does not work for the internal catalog.

### Affects Versions

0.5.0

### How to reproduce

1.create a catalog with Internal Catalog and Iceberg format
2.configure the catalog property 'table-filter'
3.it doesn't work when we list the tables in the WebUI

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
Is this a bug? I think the table-filter is a property for external catalog. WDYT? @zhoujinsong

**Comment by wangtaohz** [comment]
> Is this a bug? I think the table-filter is a property for external catalog. WDYT? @zhoujinsong

That sounds reasonable. However, from the perspective of using parameters, one may not notice this limitation, so perhaps we can throw an error when configuring this parameter in the internal catalog.

**Comment by wangtaohz** [comment]
@xbaith We don't think this is a bug. Do you have any scenarios in your **internal** catalog that require table filtering?

**Comment by baiyangtx** [comment]
> > @XBaith We don't think this is a bug. Do you have any scenarios in your internal catalog that require table filtering?
> 
> @wangtaohz Currently, we just need to avoid scanning a certain batch of tables and not persist them in the database or display them on the WebUI.

For an InternalCatalog, it will always persist tables' information, so I think this `table-filter` is not a property for InternalCatalog

**Comment by XBaith** [comment]
> For an InternalCatalog, it will always persist tables' information, so I think this `table-filter` is not a property for InternalCatalog

OKay, Would you consider skipping the scan and displaying tables whose optimize group is not registered in AMS

**Comment by baiyangtx** [comment]
> displaying tables whose optimize group is not registered in AMS

Why is there such a requirement? Currently, Catalog has a default optimizer group, so all tables will have an optimizer group. In addition to the optimizing service, there are other maintenance services on the table, such as expire.

Also, it's strange that some tables are not displayed for the internal catalog.

**Comment by XBaith** [comment]
> Also, it's strange that some tables are not displayed for the internal catalog.

Hi @baiyangtx It seems to me that the Optimization tab only shows tables managed by the Optimization service, while some tables are disabled for self-optimization or not registered in the Optimizer group. I think such a requirement is reasonable.

**Comment by baiyangtx** [comment]
For **InternalCatalog**, AMS is the metadata center for these tables. If AMS does not display the information of these tables, We will completely lose these tables and not know about their existence. 

Therefore, I believe that all tables should be displayed on the Table page for **InternalCatalog**. 

As for whether to skip the table scan, I think that for InternalCatalog, since AMS already holds all the metadata information, it is possible to obtain the information of these tables without scanning, the implementation logic of this part can be optimized. We just need to record the optimizing information and other information required for expiration in the commit interface.  @XBaith

**Comment by wangtaohz** [comment]
> Hi @baiyangtx It seems to me that the Optimization tab only shows tables managed by the Optimization service, while some tables are disabled for self-optimization or not registered in the Optimizer group. I think such a requirement is reasonable.

For the tables disabled for self-optimization (self-optimizing.enabled = false), it may be reasonable **NOT** displaying in the `Optimizing/Tables` tab. Personally, I think hiding these tables is a better option than showing them in the `idle` state. Would that meet your needs? @XBaith
