### ISSUE TITLE
[Feature]: [Flink] Flink supports 1.16 version

### ISSUE THREAD

**Issue by huyuanfeng2018** [NetEase/amoro#2027]
### Description

Currently Amoro supports flink version 1.12 1.14 1.15, and should support flink1.16

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
Thank you for raising this issue. 👍 I think it will be very meaningful for Mixed Format users. 

In addition, support for Mixed Format in Flink 1.17 is also being pushed forward. #1998 

Therefore, if we want to extract some common modules for various versions of Flink, there may be some duplicate work between the two issues. Do you have any plans for this? @huyuanfeng2018 @czy006

**Comment by czy006** [comment]
> Thank you for raising this issue. 👍 I think it will be very meaningful for Mixed Format users.
> 
> In addition, support for Mixed Format in Flink 1.17 is also being pushed forward. #1998
> 
> Therefore, if we want to extract some common modules for various versions of Flink, there may be some duplicate work between the two issues. Do you have any plans for this? @huyuanfeng2018 @czy006

This part of the work is ongoing, and when we pull out the public parts, supporting 1.16 will be a simple matter. I don't think it's necessary to do this part of the work separately at the moment
