### ISSUE TITLE
[Subtask]: Remove Flink 1.12 modules

### ISSUE THREAD

**Issue by zhoujinsong** [NetEase/amoro#2059]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Remove Flink 1.12 related modules.

### Parent issue

#1983

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
I noticed that there is Plusar related code in 1.12. How should we deal with this part
cc @zhoujinsong

**Comment by zhoujinsong** [comment]
Yes, Amoro supported Puslar as its LogStore only for Flink 1.12.
 However, this feature has not been used by users. I think we can temporarily stop supporting it and re-support it when needed.
