### ISSUE TITLE
[Improvement]: Display partitions in ordered

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/amoro#2064]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current partition display is not sorted, which makes it inconvenient to find partitions when there are many partitions.

![image](https://github.com/NetEase/amoro/assets/16421989/9f640391-edb1-47bb-993a-cdec91844ce4)

### How should we improve?

Time partition type reverse order, because it makes sense to see the latest time partition first.
Other partition type order(include bucket/truncate/identity)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
Thanks for you pick up this issue, I think order time partition is make sense. Many user use string to represent time, so should we also order string partition?

**Comment by zhongqishang** [comment]
duplicate #2316
