### ISSUE TITLE
[Improvement]: Change position delete index from set to bitmap of optimizing

### ISSUE THREAD

**Issue by shidayang** [NetEase/amoro#2078]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the optimization task of Iceberg uses a Set data structure for indexing position-delete data, which consumes a lot of memory. It could be changed to a bitmap to reduce memory usage.

### How should we improve?

Modify com.netease.arctic.iceberg.CombinedDeleteFilter position delete index

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Thank you for suggesting this optimizing, the project needs it very much now.
