### ISSUE TITLE
[Subtask]: Dashboard Catalog page supports automatically filling of required properties

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2099]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

After select `Metastore` and `Table Format` in the Catalog page, some required properties can be automatically filling to the section `Properties` with empty value, if it doesn't exist, like
<img width="1508" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/fb2789e7-ace1-4d8d-bb07-5430ce4eda24">

For different types of `Metastore`, the required properties are different as follows
| Metastore | Type                  | Required Properties |
| ---------- | ---------------- | -------------------- |
| ams           | Internal Catalog | warehouse     |
| hadoop     | External Catalog | warehouse    |
| hive           | External Catalog |    |
| glue           | External Catalog | warehouse,lock-impl,lock-table  |
| custom      | External Catalog | catalog-impl   |

And the Table Format is similar

| Table Format | Required Properties |
| ----------  | -------------------- |
| paimon      | warehouse     |

 I think this requirement can be implemented on the front-end.
### Parent issue

#2007

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
Different formats may have different keys.

**Comment by wangtaohz** [comment]
> Different formats may have different keys.

Can you offer some case? I will add it to the chart.

And I get the current chart from here `com.netease.arctic.server.dashboard.controller.CatalogController`
```java
  static {
    CATALOG_REQUIRED_PROPERTIES = Maps.newHashMap();
    CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_AMS, Lists.newArrayList(KEY_WAREHOUSE));
    CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_HADOOP, Lists.newArrayList(CatalogProperties.WAREHOUSE_LOCATION));
    CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_CUSTOM, Lists.newArrayList(CatalogProperties.CATALOG_IMPL));
  }
```

**Comment by shidayang** [comment]
> > Different formats may have different keys.
> 
> Can you offer some case? I will add it to the chart.
> 
> And I get the current chart from here `com.netease.arctic.server.dashboard.controller.CatalogController`
> 
> ```java
>   static {
>     CATALOG_REQUIRED_PROPERTIES = Maps.newHashMap();
>     CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_AMS, Lists.newArrayList(KEY_WAREHOUSE));
>     CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_HADOOP, Lists.newArrayList(CatalogProperties.WAREHOUSE_LOCATION));
>     CATALOG_REQUIRED_PROPERTIES.put(CATALOG_TYPE_CUSTOM, Lists.newArrayList(CatalogProperties.CATALOG_IMPL));
>   }
> ```
Paimon warehouse config is required regardless of the catalog type.

**Comment by wangtaohz** [comment]
> Paimon warehouse config is required regardless of the catalog type.

Ok, I will add this requirement.

**Comment by XBaith** [comment]
@wangtaohz  `GlueCatalog` also requires `warehouse` to be configured, and `lock-impl` and `lock-table` are highly recommended to need to be filled in to keep the table consistent.

**Comment by wangtaohz** [comment]
> @wangtaohz GlueCatalog also requires warehouse to be configured, and lock-impl and lock-table are highly recommended to need to be filled in to keep the table consistent.

Thank you for providing information about `GlueCatalog`. I will add it to the requirements! 

As for `lock-impl` and `lock-table`, they don't seem to be required properties. Based on your experience, do you think they should be automatically filled in by the frontend? @XBaith

**Comment by XBaith** [comment]
> As for `lock-impl` and `lock-table`, they don't seem to be required properties. Based on your experience, do you think they should be automatically filled in by the frontend? @XBaith

I don't think you can use the default `InMemoryLock` in production environments because it will lose data due to metadata location conflicts in case of concurrent commits.

**Comment by wangtaohz** [comment]
> I don't think you can use the default InMemoryLock in production environments because it will lose data due to metadata location conflicts in case of concurrent commits.

I would like to automatically fill `lock-impl` and `lock-table` by the frontend as recommended properties, but not check them by the backend as required properties.
