### ISSUE TITLE
[Subtask]: Dynamic chart in 'transactions' page

### ISSUE THREAD

**Issue by shidayang** [NetEase/amoro#2118]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

After integrating Paimon, the line chart on the Transactions page needs to display different content based on parameters from the backend, so the data structure of the line chart was separately extracted in #2116 named 'recordsSummaryForChart' and ‘filesSummaryForChart’. Like：
```
  long transactionId; // required
  int fileCount; // required
  long fileSize; // required
  long commitTime; // required
  String operation; // required
  Map<String, String> summary;

  //Determine what content to display on the front-end line chart.
  Map<String, String> recordsSummaryForChart;

  Map<String, String> filesSummaryForChart;
```

The front-end needs to use the keys in 'records/filesSummaryForChart' as category names and the values in 'records/filesSummaryForChart' as the values.

### Parent issue

#1876 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
cc @minteliuwm

**Comment by baiyangtx** [comment]
Why is it necessary for the frontend to handle different fields? Can this part of the content be processed on the backend?

**Comment by wangtaohz** [comment]
To my knowledge, Paimon's snapshot is missing the summary field, so extracting values from the summary to draw the chart is not a general solution for different table formats. My idea is to extract the values used for drawing the chart from the fields of TransactionsOfTable, thus achieving a unified front-end and back-end solution for different formats.

**Comment by shidayang** [comment]
@baiyangtx @wangtaohz Thanks for your comment, This is because Paimon has many different concepts compared to Iceberg. For example, Paimon does not have 'pos-delete' and 'eq-delete'.
