### ISSUE TITLE
[Subtask]: Support filter for `Optimizer Group` column of Optimizing Tables page

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2149]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Support filter for this `Optimizer Group` column of Optimizing Tables page would bring convenience to users who use multiple optimizer groups.

<img width="1067" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/3db78001-ae66-4e5e-b4ca-86793c80f05e">

### Parent issue

#885

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HuangFru** [comment]
Is this filter using a search box or a selection of the optimizer group list? Or other implementations?

**Comment by wangtaohz** [comment]
> Is this filter using a search box or a selection of the optimizer group list? Or other implementations?

A selection of the optimizer group list may be good enough, since there not supposed to be many groups.

**Comment by zhangmo8** [comment]
> > Is this filter using a search box or a selection of the optimizer group list? Or other implementations?
> 
> A selection of the optimizer group list may be good enough, since there not supposed to be many groups.

The option data of this selection comes from the `Optimizer Groups` Tab ?  @wangtaohz

**Comment by wangtaohz** [comment]
> The option data of this selection comes from the Optimizer Groups Tab ? @wangtaohz

Yes, and more precisely, it comes from this HTTP API `/optimize/resourceGroups`.

**Comment by wangtaohz** [comment]
BTW, the related HTTP API of this `Tables` page is `/optimize/optimizerGroups/{optimizerGroup}/tables?page={page}&pageSize={pageSize}`, and it supports filtering by `{optimizerGroup}`. When `optimizerGroup==all`, it will return the result of all optimizerGroups.

**Comment by zhangmo8** [comment]
ok. Got it

**Comment by zhangmo8** [comment]
Hi @wangtaohz  I don't find the HTTP API `ams/v1/optimize/optimizerGroups/{optimizerGroup}/tables?page={page}&pageSize={pageSize}` in the mock file.

Although I can find its definition in the `type` file, I cannot ensure that my code runs correctly.

And then, Who should I contact to match the parameter names submitted during screening?

**Comment by wangtaohz** [comment]
> Hi @wangtaohz I don't find the HTTP API ams/v1/optimize/optimizerGroups/{optimizerGroup}/tables?page={page}&pageSize={pageSize} in the mock file.

Sorry, I'm not familiar with how to mock HTTP interfaces for testing in front-end code, but I'm willing to assist in providing information about the HTTP API to complete the mock and help with future frontend development.

> Although I can find its definition in the type file, I cannot ensure that my code runs correctly.
>And then, Who should I contact to match the parameter names submitted during screening?

I can assist with reviewing and testing locally if you can submit a draft PR.

**Comment by zhangmo8** [comment]
OK.

**Comment by zhangmo8** [comment]
Can somebody give me any data from Optimizer Group.
