### ISSUE TITLE
[Bug]: Get incorrect partition field name when refresh tables

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#2165]
### What happened?

Some tables have customized partition aliases, but in `ArcticDataFiles#genericRecord` they are extracted based on the default partition aliases, which can lead to throwing NPE errors for not getting the correct fields

### Affects Versions

master/0.5.x

### What engines are you seeing the problem on?

Core

### How to reproduce

1. create a table with custom partition alias
2. enable self-optimizing
3. throw NPE when refresh table

### Relevant log output

```shell
Refreshing table dls_sjc_iceberg.diag.matsparticipantquality(tableId=1050840) failed.
java.lang.ArrayIndexOutOfBoundsException: null
```
![Uploading image.png…]()

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shidayang** [comment]
Could you provide the complete error log stack trace? Perhaps we should consider the implementation logic of the ArcticDataFiles class comprehensively.

**Comment by XBaith** [comment]
> Could you provide the complete error log stack trace? Perhaps we should consider the implementation logic of the ArcticDataFiles class comprehensively.

The full log stacks were dropped since JVM deault optimize stacks if there are too many same exception stacks, refer to https://stackoverflow.com/questions/58696093/when-does-jvm-start-to-omit-stack-traces
