### ISSUE TITLE
[Improvement]: Simplify containers config when only rely on external optimizers

### ISSUE THREAD

**Issue by tcodehuber** [NetEase/amoro#2188]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We typically use spark/flink optimizer(which runs on yarn/k8s) in prod env. There is no need to config local/flink container in config.yaml when we only rely on external optimizers. So now if don't config containers, ams can not be started, since we will encounter the NPE as below.
![image](https://github.com/NetEase/amoro/assets/5411862/996bd3d5-a511-4630-a35f-51c9253f3509)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HuangFru** [comment]
Theoretically, the default local optimizer should take effect without additional configuration and will not affect AMS startup.
