### ISSUE TITLE
[Feature]: Add support for Flink 1.18

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#2199]
### Description

Recently Flink 1.18 was released.
https://nightlies.apache.org/flink/flink-docs-release-1.18/release-notes/flink-1.18/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
I suggest that it be related to the new feature support development tasks in 1.18. By the way, do we need to remove support for 1.15 in the next version, or should we wait until the 1.18 function is stable to remove flink 1.15 support?

cc @YesOrNo828
