### ISSUE TITLE
[Improvement]: Optimize the speed of searching for tables in the tables navigation bar

### ISSUE THREAD

**Issue by hameizi** [NetEase/amoro#2215]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, each search for a table in the tables navigation bar triggers a backend request, but listing tables in the backend takes a long time. To improve performance, we could trigger a request once when opening the tables in the frontend, and subsequently search based on the returned value.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tcodehuber** [comment]
I'm glad to undertake this issue. Can you assign it to me?
