### ISSUE TITLE
[Subtask]: Automatically create tags on snapshots hour-level for iceberg Table Formats

### ISSUE THREAD

**Issue by huyuanfeng2018** [NetEase/amoro#2257]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Automatically create tags on snapshots hour-level for iceberg Table Formats

### Parent issue

https://github.com/NetEase/amoro/issues/1354

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
The related design doc https://docs.google.com/document/d/1_56YHZO7XSkkZV7bTFQ7yWNVfiV0TknwOIMt0j8Me6Y/edit#heading=h.m88xjoz356hr
