### ISSUE TITLE
[Improvement]: Show the format version of Iceberg Table

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2260]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

There are some important differences between Iceberg V1 and V2 tables, such as V2 tables supporting file deletion.
Although the default version of Iceberg has been adjusted to V2, there are still some users of V1 tables. 

Therefore, clearly displaying the format version of the table on the Amoro page helps to easily distinguish between these two types of tables.

### How should we improve?

I suggest to displaying the Iceberg table format version here, like `Iceberg(V1)` `Iceberg(V2)`
<img width="1412" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/e3d9de36-4f6b-4866-a990-858af9075fc0">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
@tcodehuber You can comment here.

**Comment by tcodehuber** [comment]
OK, I'm glad to undertake this issue.
