### ISSUE TITLE
[Improvement]: Add cache for loading table when get table meta in unkeyed table

### ISSUE THREAD

**Issue by HuangFru** [NetEase/amoro#2296]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

With a query in Trino, operations such as fetching metadata information require multiple loading tables. This can be affected by objective factors such as network latency, resulting in slower queries. 

In the Iceberg format, this caching is already implemented (native Iceberg implementation). We have this cache for our Mix-format's keyed tables, and we should add this cache for our unkeyed tables as well. This cache is also applicable to queries on the base store and change store.

### How should we improve?

Add a cache for loading tables.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
The Mixed-Iceberg format has been refactored, and the refactored Mixed-Iceberg will directly use the Iceberg Catalog, making it possible to reuse the caching capability of the Iceberg Catalog. You can refer to this issue, https://github.com/NetEase/amoro/issues/1336, to learn more about the refactored Mixed-Iceberg Catalog.

**Comment by baiyangtx** [comment]
The core implementation of the refactored MixedIceberg Catalog will look like this: [link to the code](https://github.com/NetEase/amoro/pull/1885/files#diff-6f3c24619f71b467c16d732741fda8f5b0b64a55ecf3cdb2d211ae8ed0963565).

**Comment by HuangFru** [comment]
> The core implementation of the refactored MixedIceberg Catalog will look like this: [link to the code](https://github.com/NetEase/amoro/pull/1885/files#diff-6f3c24619f71b467c16d732741fda8f5b0b64a55ecf3cdb2d211ae8ed0963565).

Native Iceberg's Caching Catalog is now only implemented on Engines(Spark, Flink), but we can reuse it. Looks like implementing a caching catalog on the refactored Mixed-Iceberg Catalog is no harm, but I think the trino module's cache also should be implemented because loading the mix table not only loads the iceberg table but also has some other operations.
