### ISSUE TITLE
[Improvement]: Helm adds Kyuubi (as a terminal backend) and PostgreSQL related conf

### ISSUE THREAD

**Issue by lukeyan2023** [NetEase/amoro#2306]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

1.  Although ams currently supports postgres, there is a lack of related configuration support in chart. The template and values.yaml database configurations in the current chart are as follows:

![image](https://github.com/NetEase/amoro/assets/108530647/ad3aa951-157e-4587-ac2e-1502b4e4ccb6)
![image](https://github.com/NetEase/amoro/assets/108530647/5d38f78c-4382-4f2d-9875-c82dc74fe57f)

2. amoro supports local and kyuubi as terminal backend, but the chart configuration supports local, as shown below

![image](https://github.com/NetEase/amoro/assets/108530647/59461808-ac76-4bf4-894e-d74ec274c2af)

Based on the above situation, the main goal this time is to add kyuubi and postgres related configurations to the helm chart.

### How should we improve?

Refer to the official website configuration to add relevant configurations to the helm chart.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by czy006** [comment]
@lukeyan2023 Hi, I would like to know if this issue is still being pushed forward? If not I will assign completion
