### ISSUE TITLE
[Bug]: optimizing-task costTime statistical mistake

### ISSUE THREAD

**Issue by chenyuzhi459** [NetEase/amoro#2318]
### What happened?

Trying to reporting optimizing-task costTime as metric, btw the  [code implementation](https://github.com/NetEase/amoro/blob/a87a2a98ad8db10dc49404f6837d39437503d3bc/ams/server/src/main/java/com/netease/arctic/server/optimizing/TaskRuntime.java#L233C30-L233C30) is confusing.
```
  public long getCostTime() {
    if (endTime != ArcticServiceConstants.INVALID_TIME) {
      long elapse = System.currentTimeMillis() - startTime;
      return Math.max(0, elapse) + costTime;
    }
    return costTime;
  }
```
It's a bit unclear what the statistical significance of the above code.  It says that the endTime is meaningful, but also calculates an elapse time based on the current time, and then adds the existing costTime? 

When task finished, the costTime and endTime would be assigned a valid value. And the `getCostTime` method may return a err value.

May be it's better to change code implementation as fllow:
```
  public long getCostTime() {
    if (endTime == ArcticServiceConstants.INVALID_TIME) {
      long elapse = System.currentTimeMillis() - startTime;
      return Math.max(0, elapse);
    }
    return costTime;
  }
```

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
Sorry for the late reply. 

I reviewed the code and indeed found an issue here. The field `costTime` represents the accumulated time of multiple executions of a task, as a task may be executed multiple times due to retries after failure.

I think the correct implementation should be: 
```java
  public long getCostTime() {
    if (endTime == ArcticServiceConstants.INVALID_TIME) { // changed here
      long elapse = System.currentTimeMillis() - startTime;
      return Math.max(0, elapse) + costTime;
    }
    return costTime;
  }
```
