### ISSUE TITLE
[Improvement][AMS]: Add configurable parameters to the ams-server.

### ISSUE THREAD

**Issue by hameizi** [NetEase/amoro#2333]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, we have some parameters hardcoded in the code, but in certain user scenarios, there is a need to modify these configurations. Therefore, we need to make these parameters configurable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangtaohz** [comment]
Do we have a related issue to make `com.netease.arctic.server.optimizing.plan.OptimizingPlanner#MAX_INPUT_FILE_SIZE_PER_THREAD` configurable? It may be a table level configuration.
