### ISSUE TITLE
[Improvement]: Configure `iceberg.worker.num-threads` in the configuration file

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/amoro#2386]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When `Runtime.getRuntime().availableProcessors()` is not obtained correctly or the obtained value is less than or equal to 2, the default value of iceberg is 2, AMS is congested in thread `iceberg-work-pool-xx`.

### How should we improve?

Add parameters in `config.yaml` to overwrite the value of `iceberg.worker.num-threads`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HuangFru** [comment]
This is a java property used by the Iceberg and it can be set in `ams.sh` like '-Diceberg.worker.num-threads=xxx'.
