### ISSUE TITLE
[Improvement]: Use partition filter to speed up optimizing plan

### ISSUE THREAD

**Issue by HuangFru** [NetEase/amoro#2417]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

AMS currently uses `PartitionFilter` to filter unnecessary files when planning the table before optimizing. But this only filters files and cannot speed up the plan because all the files have been planned. We should consider supporting partition filters on the scan.
<img width="1007" alt="image" src="https://github.com/NetEase/amoro/assets/68625618/7b02e831-cb3e-43ab-b7fa-0deacd379668">

### How should we improve?

Support partition filter on scan to speed up plan.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by huyuanfeng2018** [comment]
I discussed this issue with @zhoujinsong before, let’s see if he has any opinions. The partition filter conditions cannot be passed in iceberg scan, but the manifest list contains the maximum and minimum values ​​​​of the saved partitions. You can use this as an entry point to obtain it.

**Comment by zhoujinsong** [comment]
Yes, @wangtaohz and @HuangFru shared a feasible transformation method to me. I think this issue is related to that. I am looking forward to the implementation of this improvement.

BTW, this issue is related to #1842.

**Comment by wangtaohz** [comment]
> Yes, @wangtaohz and @HuangFru shared a feasible transformation method to me today. I think this issue is related to that. I am looking forward to the implementation of this improvement.

We can transform partition data into a data filter expression, @HuangFru will submit a PR to support it.
