### ISSUE TITLE
[Bug]: Display error on the page for creating the Catalog

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/amoro#2490]
### What happened?

<img width="1743" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/4bda56d1-d509-4533-91e6-44cccd1d8d7b">
It shoule be.
<img width="1275" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/f1f74dc3-a9dc-4de6-b0aa-a6653f99e3ef">

### Affects Versions

master/0.7.0

### What engines are you seeing the problem on?

AMS

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aireed** [comment]
cc @minteliuwm  Could you have time to take a look？
