### ISSUE TITLE
[Improvement]: Extract the OptimizingExpiring keep time and interval to config able.

### ISSUE THREAD

**Issue by GavinH1984** [NetEase/amoro#2527]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currentlly the Optimizing metadata cleanup time is keep 30 days data and clean up interval is one day, there no way to change the default config.

there shoud be able to config the Optimizing metadata keep time and cleanup interval.

### How should we improve?

make the Optimizing metadata keep time and cleanup interval configable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongqishang** [comment]
@GavinH1984 

Thanks for propose this improvement. This parameter was previously added in PR #2335.
But the PR has not updated for a while. If possible, you can continue based on the previous one, or new .

**Comment by zhoujinsong** [comment]
Closed as had been supported.
