### ISSUE TITLE
[Bug]: Optimization task loss leads to the optimization process remaining in a running state indefinitely

### ISSUE THREAD

**Issue by rfyu** [NetEase/amoro#2565]
### What happened?

Task-14 does not exist in the `taskQueue` of AMS, so this task remains in the planned state.
![uTools_1708763128753](https://github.com/NetEase/amoro/assets/39233058/351d5e07-647f-4e5e-b036-e28ec76381fd)

The root cause of this bug is that even if `retryTaskQueue.poll()` returns a task,`fetchScheduledTask()` will still be called as usual. Once `fetchScheduledTask()` also fetches a task, this task will be lost. 
![uTools_1708764475759](https://github.com/NetEase/amoro/assets/39233058/8904b245-8820-40bb-a644-30d383756f37)

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Relevant log output

![uTools_1708765703735](https://github.com/NetEase/amoro/assets/39233058/1fb4d3a1-4a1d-4b83-ab4f-9fdfd3cc0380)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majin1102** [comment]
Good job

This is really a fatal problem!
