### ISSUE TITLE
[Feature][AMS]: Add the metric statistics of a table

### ISSUE THREAD

**Issue by hameizi** [NetEase/amoro#477]
### Description

Add table metric statistics, such as file size and file quantity

### Use case/motivation

Add table metric statistics, such as file size and file quantity

### Describe the solution

The metric of the table is collected periodically and written to the database

### Related issues

subtask of https://github.com/NetEase/arctic/issues/405

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
