### ISSUE TITLE
[Improvement][Flink]: Adapt New Version Message Format with TransactionId

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/amoro#481]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

LogStore message format should be upgraded to new version to support transactionId,  the consistency double write will do retract      
according to transactionId instead of checkpoint number. 

this will make double write action as log strore essential features，not a feature of flink engine. 

### How should we improve?

Change epicNo  from checkpoint number to transaction number. and adapt the related code 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
