### ISSUE TITLE
[Improvement]: the catalog properties should not be added in table properties

### ISSUE THREAD

**Issue by hameizi** [NetEase/amoro#498]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?page=4&q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

the catalog properties like `meta_store_site`,`krb_keytab` should not be added in table properties

### How should we improve?

when update or add table properties the catalog properties like `meta_store_site`,`krb_keytab` should be ignore

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Aireed** [comment]
should we provide a method to do some filter ?

**Comment by zhoujinsong** [comment]
https://github.com/NetEase/amoro/issues/487
