### ISSUE TITLE
[Feature]: Enrich Catalog types

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#507]
### Description

Now, Arctic only completely support hadoop catalog type.But there are some types of catalog that need to be implemented or refined: such as **AWS GlueCatalog**.

### Use case/motivation

Supports which arctic tables need to be stored on AWS.

### Describe the solution

1. Implement an ArcticFileIO named `ArcticS3FileIO` to support writing data to S3.
2. Implement an ArcticCatalog which called `ArcticGlueCatalog` to support managing Glue tables.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by XBaith** [comment]
Hi @wangtaohz plz check this issue and give some suggestions

**Comment by baiyangtx** [comment]
We are doing a Catalog and Mixed-format code refactor,  this maybe solve your problem.  

You can track the process in this https://github.com/NetEase/arctic/issues/1061

**Comment by XBaith** [comment]
> We are doing a Catalog and Mixed-format code refactor, this maybe solve your problem.
> 
> You can track the process in this #1061

Thanks

**Comment by zhoujinsong** [comment]
@XBaith 
As you are using the Iceberg format tables, you can manage iceberg tables with all kinds of catalog type now:

- Choose meta store type to `Hive` if you are using Iceberg HiveCatalog
- Choose meta store type to `Hadoop` if you are using Iceberg HadoopCatalog
- Choose meta store type to `Custom` if you are using other Iceberg Catalogs like AWS/JDBC/REST and remember set the `catalog-impl` property in your catalog setting.

**Comment by zhoujinsong** [comment]
Closed as have been supported.
