### ISSUE TITLE
[Improvement]: The docs website should have multi-versions 

### ISSUE THREAD

**Issue by YesOrNo828** [NetEase/amoro#649]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We should support multi versions of the docs website.
Nowadays, the 0.4.0 version is going to release, but massive guides are different from the 0.3.* version.

### How should we improve?

The guide website is based on the `mkdocs` component. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Closed as have been supported.
