### ISSUE TITLE
[Improvement][Flink]: Externalize HMS、Kafka env to decrease the cost of Flink UTs

### ISSUE THREAD

**Issue by zstraw** [NetEase/amoro#696]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Flink Uts start/close kafka or hms env for many times which wastes time, and it can be optimized for only once before/after all tests.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YesOrNo828** [comment]
[ut_costs.log](https://github.com/NetEase/amoro/files/12581774/ut_costs.log)
This is a statistic of the time spent on each single test, from CI log achieve.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
