### ISSUE TITLE
[Feature]: Support ORC file format for Mixed format tables

### ISSUE THREAD

**Issue by zhongqishang** [NetEase/amoro#740]
### Description

Now Iceberg only supports the PARQUET format, ORC is a very common format.
Hope can support.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Given that Iceberg already has good support for ORC and AVRO file formats. Arctic may support both formats with a relatively small cost.
