### ISSUE TITLE
[Improvement][Spark]: Improvement of arctic table properties watemark 

### ISSUE THREAD

**Issue by baiyangtx** [NetEase/amoro#762]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

![image](https://user-images.githubusercontent.com/7732224/204284101-bedea12f-8bca-444e-8307-20600257aab0.png)

table properties watermark could display as human friendly

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baiyangtx** [comment]
Should spark change the format of the raw table property?  maybe formatted in `show table status ` is better?

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
