### ISSUE TITLE
[Feature]: Display more details about table meta infomartion

### ISSUE THREAD

**Issue by XBaith** [NetEase/amoro#863]
### Description

- Iceberg could not list files in every partitions on webpage now, I believe that it is usefull for users to know currernt table data summay.
- Sometimes users want to know: _iceberg format version_, _history of table schema_, etc...
maybe could consider displaying them.

### Use case/motivation

Help users understand the data situation of the table

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
Yes, listing all partitions and files for the iceberg format table is a very expensive operation, so we did not support that for now. 
I am agree with that more summary information will help a lot. 
We display the `Average File Size`, `Files`, `Last Commit Time`, and `Table Size` for now, we can add more summary information, Iceberg provides a lot snapshot summary: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotSummary.java
and the ones start with `total-` is very useful to show the summary information for table.

**Comment by zhoujinsong** [comment]
Arctic shows the DDL history of tables in `Operations` tab now.
So you prefer to see the history table schema rather than only the DDL? @XBaith

**Comment by XBaith** [comment]
> 

Have any other iceberg data summay we could use?
I think we could list all files in iceberg meta table:
```
such as this query statement below:
select * from iceberg.database.table.files
```

and then group files by partition?

**Comment by XBaith** [comment]
> 

I think display history of schema is more obvious, but only keep the DDL is fine. We can discuss this feature if have other user need to in the future

**Comment by zhoujinsong** [comment]
> > 
> 
> Have any other iceberg data summay we could use? I think we could list all files in iceberg meta table:
> 
> ```
> such as this query statement below:
> select * from iceberg.database.table.files
> ```
> 
> and then group files by partition?

Selecting the `table.files` metadata table is an expensive operation when the table has a large amount of files.
That's the core reason why do not display `Files` tab for iceberg tables right now.
But we can keep discussing finding an acceptable way to help the user understanding the status of the files and data in the table.

**Comment by majin1102** [comment]
> > 
> 
> Have any other iceberg data summay we could use? I think we could list all files in iceberg meta table:
> 
> ```
> such as this query statement below:
> select * from iceberg.database.table.files
> ```
> 
> and then group files by partition?

This is a good suggestion from a product view,  Arctic currently shows more information including partition and file list for Mixed format, because they are fully stored in AMS sysdb, which could implement page splitting elegantly. If we want to do the same for native Ice format, a fuzzy page splitting should be necessary.  and this could be applied back to Mixed format and save db storage
