### ISSUE TITLE
[Feature]: Introduce balanced scheduling policy to makes the optimize mechanism of the table more balanced

### ISSUE THREAD

**Issue by shidayang** [NetEase/amoro#946]
### Description

The current self-optimizing resource usage is controlled by a quota parameter. In our benchmark, We found that some tables that need to be optimized have not been optimized, which seriously affects the benchmark performance. We solve this problem by configuring the quota parameter.  but quota is difficult to determine the specific value.

The current quota mechanism is only used to control the resources used by each table for optimizing within a long period of time to meet its numerical configuration. This is a resource-based allocation strategy, not an on-demand allocation strategy.
If there is a table consumes a lot of resources, it will not trigger optimization for a long period of time after optimizing once. 

**Goal:**
Introduce the Optimizer Group with automatic quota, Every table optimization will be balanced in the group, Balanced means that the optimization intervals of each table are roughly the same. 

**Strategy**
Tables that have not been optimized for a long time in the automatic quota will be optimized first

Detailed design will be followed by design documents

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shidayang** [comment]
@wangtaohz cc

**Comment by shidayang** [comment]
@hzluting cc

**Comment by majin1102** [comment]
Establish an income function for each table, and optimize those tables with high income first.

can you explain this more? How automation works?

**Comment by shidayang** [comment]
> Establish an income function for each table, and optimize those tables with high income first.
> 
> can you explain this more? How automation works?

Thanks for your replay.
The income function can measure the income obtained by optimizing a table. Of course, the table with higher income should be optimized first.

We can design the income function according to the following rules：
1. Reduced number of files, the cost of opening a file can be roughly converted into the cost of reading 4M data.
2. Reduced amount of read data.

**Table1:**
![image](https://user-images.githubusercontent.com/26699250/208053821-b6ee074e-c8ea-48de-9971-25a369357a7f.png)
Only four insert files. optimization can reduce three files, so the income of optimization is 4M * 3=12M

*Table2:**
![image](https://user-images.githubusercontent.com/26699250/208054352-ffdbf3c1-1132-4d09-963a-f6e82a11844d.png)
In Iceberg format, Reduced three files can get income 4M *3，There is a total of (1M + 2M) delete data, since the insert file will repeatedly read the delete data, the total income will be (1M + 2M)*2. The total income is 4M*3 + (1M +2M)*2 = 18M

18M > 12M so Table2 will be optimized first.
If the user sets the weight of Table1 to 2 then the income of Table1 is 12M *2 = 24M, so Table1  will be optimized first.

**Comment by majin1102** [comment]
Thanks for your ideas.

you mean income = earnings right?

Maybe it's better to clarify your automatic quota goal first. And I wish your solution could be simply understood if this is a necessary improvement

**Comment by shidayang** [comment]
Goal：
Introduce the Optimizer Group with automatic quota, Every table optimization will be balanced in the group, Balanced means that the optimization intervals of each table are roughly the same.

I agree with you that we need a simple solution. Perhaps it is a good solution to prioritize according to the length of time since the last execution of optimization. The longer the time, the higher the priority.

**Comment by shidayang** [comment]
Let's discuss the details.
The current optimizer scheduling process looks like this:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/26699250/210296647-6baa42df-07b5-47f1-99d4-515dd386d211.png">
When the optimizer obtains tasks from ams, the sort-queue will sort the tasks  according to the quota usage size.
When we introduce the optimize-group of automatic quota, the sort-queue in the optimize-group of automatic quota will be sorted according to the time since the last optimization. The longer the time since the last optimization, the more priority will be executed.

**How to define automatic optimize-group**
Currently optimize-group is defined through the configuration file, it is like this:
```
optimize_group:
  - name: default
    container: localContainer
    properties:
      memory: 1024
```
We can introduce a param named `schedule-type`, it default value is `quota`, and user can set the value to 'auto-quota'. Such as:
```
optimize_group:
  - name: default
    container: localContainer
    properties:
      memory: 1024
      schedule.type: auto-quota
```

**Comment by shidayang** [comment]
cc @majin1102 @zhoujinsong @wangtaohz

**Comment by zhoujinsong** [comment]
> Let's discuss the details. The current optimizer scheduling process looks like this: <img alt="image" width="663" src="https://user-images.githubusercontent.com/26699250/210296647-6baa42df-07b5-47f1-99d4-515dd386d211.png"> When the optimizer obtains tasks from ams, the sort-queue will sort the tasks according to the quota usage size. When we introduce the optimize-group of automatic quota, the sort-queue in the optimize-group of automatic quota will be sorted according to the time since the last optimization. The longer the time since the last optimization, the more priority will be executed. If a table belongs to the optimize-group of automatic quota, the quota parameter configured on the table will not take effect
> 
> **How to define automatic quota optimize-group** Currently optimize-group is defined through the configuration file, it is like this:
> 
> ```
> optimize_group:
>   - name: default
>     container: localContainer
>     properties:
>       memory: 1024
> ```
> 
> We introduce a param named `schedule-type`, it default value is `quota`, and user can set the value to 'auto-quota'. Such as:
> 
> ```
> optimize_group:
>   - name: default
>     container: localContainer
>     properties:
>       memory: 1024
>       schedule.type: auto-quota
> ```

This design looks good to me.

**Comment by shidayang** [comment]
> > Let's discuss the details. The current optimizer scheduling process looks like this: <img alt="image" width="663" src="https://user-images.githubusercontent.com/26699250/210296647-6baa42df-07b5-47f1-99d4-515dd386d211.png"> When the optimizer obtains tasks from ams, the sort-queue will sort the tasks according to the quota usage size. When we introduce the optimize-group of automatic quota, the sort-queue in the optimize-group of automatic quota will be sorted according to the time since the last optimization. The longer the time since the last optimization, the more priority will be executed. If a table belongs to the optimize-group of automatic quota, the quota parameter configured on the table will not take effect
> > **How to define automatic quota optimize-group** Currently optimize-group is defined through the configuration file, it is like this:
> > ```
> > optimize_group:
> >   - name: default
> >     container: localContainer
> >     properties:
> >       memory: 1024
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We introduce a param named `schedule.type`, it default value is `quota`, and user can set the value to 'auto-quota'. Such as:
> > ```
> > optimize_group:
> >   - name: default
> >     container: localContainer
> >     properties:
> >       memory: 1024
> >       schedule.type: auto-quota
> > ```
> 
> This design looks good to me. But do we still need to split up the implementation steps in more detail? Perhaps we can first complete the abstraction of the sorting process with a PR.

Ok, I will complete the abstraction of the sorting process with a PR

**Comment by majin1102** [comment]
I don't think using a property like schedule.type would be a good idea.  this could be a top parameter @shidayang. And according to your description, auto-quota has no meaning for this balancing policy.  I would make configurations like this:

> optimize_group:
>   - name: default
>     container: localContainer
>     scheduling_policy: balanced/quota
>     properties:
>       memory: 1024

**Comment by shidayang** [comment]
> 

Good idea!

**Comment by shidayang** [comment]
> I don't think using a property like schedule.type would be a good idea. this could be a top parameter @shidayang. And according to your description, auto-quota has no meaning for this balancing policy. I would make configurations like this:
> 
> ```
>   optimize_group:
>       name: default
>       container: localContainer
>       scheduling_policy: balanced/quota
>       properties:
>         memory: 1024
> ```

Good idea!
