### ISSUE TITLE
[Improvement][Optimize]:Hive can't read data when full optimize is the first execution

### ISSUE THREAD

**Issue by hzluting** [NetEase/amoro#953]
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I created an unKeyed table and used Hive insert overwrite to a new partition, so the hive partition location is xxx/table/hive/p1.
But when full optimize is executing, a tmp child location xxx/table/hive/p1/xxxxx_xxxx is created in xxx/table/hive/p1. 
So Hive can't read this partition before the optimize task commit success in Hive because there has a directory in the Hive partition location.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoujinsong** [comment]
@hzluting Is the problem due to the fact that there are other folders under the hive location, so it affects the reading process of hive?

**Comment by hzluting** [comment]
> @hzluting Is the problem due to the fact that there are other folders under the hive location, so it affects the reading process of hive partition?

Yes, because the optimizing produces a new folder under the hive location in the process.

**Comment by zhoujinsong** [comment]
Closed as not updated for a long time.
